# Generated by Django 5.2.15 on 2026-06-25 19:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Country code must be ISO 3166-1 alpha-2.", regex="^[A-Z]{2}$"
                            )
                        ],
                    ),
                ),
                ("name_tr", models.CharField(max_length=120)),
                ("name_en", models.CharField(max_length=120)),
                ("region_code", models.CharField(blank=True, max_length=40)),
                ("is_eu_member", models.BooleanField(default=False)),
                ("is_europe", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ["name_tr"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=120)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("municipality", "Municipality"),
                            ("development_agency", "Development agency"),
                            ("university", "University"),
                            ("ngo", "NGO"),
                            ("foundation", "Foundation"),
                            ("multilateral", "Multilateral"),
                            ("company", "Company"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("website_url", models.URLField(blank=True, max_length=500)),
                ("logo", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institutions",
                        to="institutions.country",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(fields=("country", "name"), name="uniq_institution_country_name")
                ],
            },
        ),
    ]
