# Generated by Django 5.2.15 on 2026-06-26 00:24

import django.db.models.deletion
from django.db import migrations, models

import apps.blog.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calls", "0003_postgres_search_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("title", models.CharField(blank=True, max_length=160)),
                ("bio", models.TextField(blank=True)),
                ("photo", models.FileField(blank=True, upload_to="blog/authors/")),
                ("photo_alt_text", models.CharField(blank=True, max_length=180)),
                ("website_url", models.URLField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="blog_author_slug_idx"),
                    models.Index(fields=["is_active"], name="blog_author_active_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=240, unique=True)),
                ("excerpt", models.TextField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[("guide", "Proje rehberi"), ("funding", "Hibe ve fon"), ("news", "Duyuru")],
                        default="guide",
                        max_length=40,
                    ),
                ),
                ("cover_image", models.FileField(blank=True, upload_to="blog/covers/")),
                ("cover_alt_text", models.CharField(blank=True, max_length=180)),
                ("cover_caption", models.CharField(blank=True, max_length=220)),
                ("cover_source_url", models.URLField(blank=True, max_length=500)),
                ("body_html", models.TextField(validators=[apps.blog.models.validate_rich_text_allowlist])),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("scheduled", "Scheduled"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("reading_time_minutes", models.PositiveSmallIntegerField(default=1)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("canonical_url", models.URLField(blank=True, max_length=500)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="posts", to="blog.blogauthor"
                    ),
                ),
                ("related_calls", models.ManyToManyField(blank=True, related_name="blog_posts", to="calls.grantcall")),
            ],
            options={
                "ordering": ["-publish_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="blog_post_slug_idx"),
                    models.Index(fields=["status", "publish_at"], name="blog_post_status_publish_idx"),
                    models.Index(fields=["category"], name="blog_post_category_idx"),
                ],
            },
        ),
    ]
