# Generated by Django 5.2.15 on 2026-06-25 20:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calls", "0002_grantcall_call_funding_min_lte_max_and_more"),
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_name", models.CharField(max_length=80)),
                ("source_url", models.URLField(max_length=700)),
                ("source_excerpt", models.TextField(max_length=2000)),
                ("selector_or_path", models.CharField(blank=True, max_length=255)),
                ("fetched_at", models.DateTimeField()),
                ("content_hash", models.CharField(max_length=128)),
                ("parser_version", models.CharField(max_length=80)),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "grant_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="field_evidence", to="calls.grantcall"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="field_evidence", to="sources.source"
                    ),
                ),
            ],
            options={
                "ordering": ["grant_call", "field_name", "-fetched_at"],
                "indexes": [
                    models.Index(fields=["field_name"], name="evidence_field_name_idx"),
                    models.Index(fields=["content_hash"], name="evidence_content_hash_idx"),
                    models.Index(fields=["fetched_at"], name="evidence_fetched_at_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("grant_call", "field_name", "content_hash", "parser_version"),
                        name="uniq_field_evidence_call_field_hash_parser",
                    )
                ],
            },
        ),
    ]
