# Generated by Django 5.2.15 on 2026-06-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0003_postgres_search_indexes"),
        ("ingestion", "0002_reviewitem"),
        ("sources", "0002_source_source_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("schedule", "Schedule"),
                            ("manual", "Manual"),
                            ("retry", "Retry"),
                            ("backfill", "Backfill"),
                        ],
                        default="schedule",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("completed", "Completed"), ("failed", "Failed")],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("discovered_count", models.PositiveIntegerField(default=0)),
                ("fetched_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("http_status_summary", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_summary", models.TextField(blank=True)),
                ("worker_id", models.CharField(blank=True, max_length=120)),
                ("config_version", models.PositiveIntegerField(default=1)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="crawl_runs", to="sources.source"
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawlItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_url", models.URLField(max_length=700)),
                ("normalized_url", models.URLField(max_length=700)),
                ("external_id", models.CharField(blank=True, max_length=200)),
                ("content_hash", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("fetched", "Fetched"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="discovered",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("parser_version", models.CharField(blank=True, max_length=80)),
                ("raw_metadata_json", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                (
                    "grant_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crawl_items",
                        to="calls.grantcall",
                    ),
                ),
                (
                    "crawl_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="ingestion.crawlrun"
                    ),
                ),
            ],
            options={
                "ordering": ["crawl_run", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="crawlrun",
            index=models.Index(fields=["source", "status"], name="crawl_run_source_status_idx"),
        ),
        migrations.AddIndex(
            model_name="crawlrun",
            index=models.Index(fields=["started_at"], name="crawl_run_started_idx"),
        ),
        migrations.AddIndex(
            model_name="crawlitem",
            index=models.Index(fields=["crawl_run", "status"], name="crawl_item_run_status_idx"),
        ),
        migrations.AddIndex(
            model_name="crawlitem",
            index=models.Index(fields=["normalized_url"], name="crawl_item_norm_url_idx"),
        ),
        migrations.AddIndex(
            model_name="crawlitem",
            index=models.Index(fields=["content_hash"], name="crawl_item_hash_idx"),
        ),
    ]
