# Generated by Django 5.2.15 on 2026-06-25 19:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("base_url", models.URLField(max_length=500)),
                ("listing_url", models.URLField(max_length=500)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("feed", "Feed"),
                            ("sitemap", "Sitemap"),
                            ("html", "HTML"),
                            ("headless", "Headless"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("adapter_key", models.SlugField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("degraded", "Degraded"),
                            ("blocked", "Blocked"),
                            ("retired", "Retired"),
                            ("manual_only", "Manual only"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "crawl_interval_minutes",
                    models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15)]),
                ),
                (
                    "robots_status",
                    models.CharField(
                        choices=[("allowed", "Allowed"), ("restricted", "Restricted"), ("unknown", "Unknown")],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "terms_status",
                    models.CharField(
                        choices=[("reviewed", "Reviewed"), ("restricted", "Restricted"), ("unknown", "Unknown")],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("contact_url", models.URLField(blank=True, max_length=500)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                (
                    "health_score",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("config_json", models.JSONField(blank=True, default=dict)),
                ("config_version", models.PositiveIntegerField(default=1)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["institution__name", "name"],
                "indexes": [
                    models.Index(fields=["status", "source_type"], name="source_status_type_idx"),
                    models.Index(fields=["adapter_key"], name="source_adapter_key_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("institution", "name"), name="uniq_source_institution_name"),
                    models.UniqueConstraint(fields=("adapter_key", "listing_url"), name="uniq_source_adapter_listing"),
                ],
            },
        ),
    ]
