# Generated by Django 5.2.15 on 2026-06-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="source_key",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
