# Generated by Django 5.2.15 on 2026-06-25 19:57

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        ("sources", "0001_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrantCall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=320)),
                ("external_id", models.CharField(blank=True, max_length=200)),
                ("official_url", models.URLField(max_length=700)),
                ("canonical_source_url", models.URLField(max_length=700)),
                ("fingerprint", models.CharField(max_length=128, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("purpose", models.TextField(blank=True)),
                ("eligibility_text", models.TextField(blank=True)),
                ("conditions_text", models.TextField(blank=True)),
                ("duration_text", models.TextField(blank=True)),
                ("funding_text", models.TextField(blank=True)),
                ("application_process_text", models.TextField(blank=True)),
                ("contact_text", models.TextField(blank=True)),
                ("source_published_at", models.DateTimeField(blank=True, null=True)),
                ("application_open_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_timezone", models.CharField(blank=True, default="UTC", max_length=64)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("duration_min_months", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration_max_months", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("funding_min", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("funding_max", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "funding_rate_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "workflow_status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("review", "Review"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="discovered",
                        max_length=20,
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("open", "Open"),
                            ("closing_soon", "Closing soon"),
                            ("closed", "Closed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title_confidence",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "deadline_confidence",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "eligibility_confidence",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "funding_confidence",
                    models.PositiveSmallIntegerField(
                        default=0, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "audiences",
                    models.ManyToManyField(blank=True, related_name="grant_calls", to="taxonomy.audiencetype"),
                ),
                (
                    "countries",
                    models.ManyToManyField(blank=True, related_name="grant_calls", to="institutions.country"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grant_calls",
                        to="institutions.institution",
                    ),
                ),
                (
                    "organization_sizes",
                    models.ManyToManyField(blank=True, related_name="grant_calls", to="taxonomy.organizationsize"),
                ),
                (
                    "program_types",
                    models.ManyToManyField(blank=True, related_name="grant_calls", to="taxonomy.programtype"),
                ),
                ("regions", models.ManyToManyField(blank=True, related_name="grant_calls", to="taxonomy.region")),
                ("sectors", models.ManyToManyField(blank=True, related_name="grant_calls", to="taxonomy.sector")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="grant_calls", to="sources.source"
                    ),
                ),
                ("themes", models.ManyToManyField(blank=True, related_name="grant_calls", to="taxonomy.theme")),
            ],
            options={
                "ordering": ["-published_at", "-first_seen_at"],
                "indexes": [
                    models.Index(fields=["deadline_at"], name="call_deadline_idx"),
                    models.Index(fields=["first_seen_at"], name="call_first_seen_idx"),
                    models.Index(fields=["published_at"], name="call_published_idx"),
                    models.Index(fields=["workflow_status"], name="call_workflow_idx"),
                    models.Index(fields=["availability_status"], name="call_availability_idx"),
                    models.Index(fields=["institution"], name="call_institution_idx"),
                    models.Index(fields=["source"], name="call_source_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("source", "external_id"),
                        name="uniq_call_source_external_id",
                    ),
                    models.UniqueConstraint(fields=("canonical_source_url",), name="uniq_call_canonical_source_url"),
                ],
            },
        ),
    ]
