# Generated by Django 5.2.15 on 2026-06-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0001_initial"),
        ("institutions", "0001_initial"),
        ("sources", "0001_initial"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="grantcall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("funding_min__isnull", True),
                    ("funding_max__isnull", True),
                    ("funding_min__lte", models.F("funding_max")),
                    _connector="OR",
                ),
                name="call_funding_min_lte_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="grantcall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("duration_min_months__isnull", True),
                    ("duration_max_months__isnull", True),
                    ("duration_min_months__lte", models.F("duration_max_months")),
                    _connector="OR",
                ),
                name="call_duration_min_lte_max",
            ),
        ),
    ]
