# Generated by Django 5.2.15 on 2026-06-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("DAILY", "Günlük"), ("WEEKLY", "Haftalık"), ("MONTHLY", "Aylık")],
                        default="WEEKLY",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Onay bekliyor"),
                            ("confirmed", "Onaylandı"),
                            ("unsubscribed", "Abonelikten çıktı"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("consent_accepted", models.BooleanField(default=False)),
                ("confirmation_token_hash", models.CharField(blank=True, max_length=64)),
                ("unsubscribe_token_hash", models.CharField(blank=True, max_length=64)),
                ("token_created_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "frequency"], name="newsletter_status_freq_idx"),
                    models.Index(fields=["confirmation_token_hash"], name="newsletter_confirm_hash_idx"),
                    models.Index(fields=["unsubscribe_token_hash"], name="newsletter_unsub_hash_idx"),
                ],
            },
        ),
    ]
