# Generated by Django 5.2.15 on 2026-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterDigestRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("DAILY", "Günlük"), ("WEEKLY", "Haftalık"), ("MONTHLY", "Aylık")], max_length=20
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Çalışıyor"), ("completed", "Tamamlandı"), ("failed", "Başarısız")],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("subscriber_count", models.PositiveIntegerField(default=0)),
                ("call_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-period_end", "-created_at"],
                "indexes": [models.Index(fields=["frequency", "status"], name="newsletter_run_freq_status_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("frequency", "period_start", "period_end"), name="uniq_newsletter_digest_period"
                    )
                ],
            },
        ),
    ]
