# Generated by Django 5.2.15 on 2026-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0002_newsletterdigestrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSuppression",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_hash", models.CharField(max_length=64, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unsubscribe", "Abonelikten çıkış"),
                            ("bounce", "Bounce"),
                            ("complaint", "Şikayet"),
                            ("manual", "Manuel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["reason", "created_at"], name="newsletter_suppress_reason_idx")],
            },
        ),
    ]
