# Generated by Django 5.2.15 on 2026-06-25 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudienceType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("name_tr", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "audience type",
                "verbose_name_plural": "audience types",
                "ordering": ["name_tr"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationSize",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("name_tr", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "organization size",
                "verbose_name_plural": "organization sizes",
                "ordering": ["name_tr"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("name_tr", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "program type",
                "verbose_name_plural": "program types",
                "ordering": ["name_tr"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("name_tr", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "region",
                "verbose_name_plural": "regions",
                "ordering": ["name_tr"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("name_tr", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "sector",
                "verbose_name_plural": "sectors",
                "ordering": ["name_tr"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("name_tr", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "theme",
                "verbose_name_plural": "themes",
                "ordering": ["name_tr"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KeywordRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("pattern", models.CharField(max_length=255)),
                (
                    "match_field",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("summary", "Summary"),
                            ("eligibility", "Eligibility"),
                            ("funding", "Funding"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "audience",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="taxonomy.audiencetype"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="taxonomy.sector"
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="taxonomy.theme"
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
    ]
